### PR TITLE
Updated the list using the script provided

### LINKED ISSUE #31: LicenseList.pm is outdated
I get this:
```
    # license ‘GPL-3.0-or-later’ is not one of the standardized SPDX license identifiers.
    # please use use one of the identifiers from https://spdx.org/licenses/
    # for the license field or if your license is not on the list,
    # include a URL to the license text as one of the 'support' keys
    # in addition to listing its name.
    # 
    not ok 6 - License is correct
```

`GPL-3.0-or-later` is a valid option now. In fact, `GPL-3.0` is now deprecated and this module should start giving a warning.

### PR DESCRIPTION
**Pull request by kensanata**
This fixes #31.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I wonder if this is going to make tests fail for many modules out there…

**Comment by AlexDaniel** [comment]
If it does, I recommend putting removed licenses back into the list, submitting PRs to all affected modules and maybe later removing these licenses from the list.

**Comment by jonathanstowe** [comment]
I'm considering the list into a hash with a boolean value so false ones are considered "deprecated" with an appropriate warning, thus outsourcing the PR part.

**Comment by jonathanstowe** [comment]
Hi,
sorry for leaving this so long.  I've decided to solve this in a different way, by spinning off the licence piece into a separate distribution that uses the JSON version of the license list directly and which has a 'deprecated' flag in it.

**Comment by jonathanstowe** [comment]
Hi,
I actually manually merged this (as 3f3cd1171f53b32a6c4d1d8528db83ccd420b03e as I rebased.)  Then decided to implement it a different way by putting the list in another module altogether.  ```License::SPDX``` basically embeds the license list as JSON in a module and has the "deprecated license" functionality and everything.

So if nothing else thanks for inspiring me to improve the way that the license checking is done.

**Pull request closed without merging**
