### PR TITLE
Cross-platform CI fixes +  README documentation updates

### PR DESCRIPTION
**Pull request by azawawi**
Enjoy :+1:

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Thanks!

**Comment by azawawi** [comment]
Thanks Jedi Master :+1:

**Comment by jonathanstowe** [comment]
Think I have it working on appveyor :)  https://ci.appveyor.com/project/jonathanstowe/test-meta

Thanks again.

**Comment by azawawi** [comment]
Cool.

**Pull request merged**
