### PR TITLE
Add License checks and use new META license spec

### PR DESCRIPTION
**Pull request by samcv**
* Add code to check the license name against the SPDX list

* Add SPDX license list for checking against license field
 * This is the current complete SPDX license list, with code included for
   regenerating it as needed in the future.
 * The purpose of this list is to be able to check that a SPDX license name
   has been used, and if it is not valid, notify the user to use a
   standardized name.

* If the user has checked and there is no standardized identifier, then they
  should give a URL to the source text of the license.

* Allow use of NONE or NOASSERTION for license with warning.
  Don't fail the test, but do show a notice that this is not the recommended
  situation.
 * Note that NONE and NOASSERTION are the SPDX standardized notation for no
 license or if the license is unknown.

Meta meta changes:

* Change *this* project's META6.json file to use Artistic-2.0 in license field

* Artistic-2.0 is the SPDX standardized name.

For more info on this spec see https://design.perl6.org/S22.html#license

This Pull Request requires this change to the META6 module before it can be merged:
https://github.com/jonathanstowe/META6/pull/5

### CODE REVIEW

**Comment by jonathanstowe** [comment]
I'm not going to merge this immediately as I'm a bit concerned that it may fail a large number of otherwise perfectly valid modules in order to enforce a new policy that hasn't really had a great deal of discussion yet.

In the first instance I'd like to run this against the whole ecosystem to see what the potentional impact might be.

I think it might also be worth considering adding a "meta-version" attribute and only doing this test if that is defined and if it is e.g. greater than 1.

**Comment by samcv** [comment]
@jonathanstowe sounds like a good ideal to me. There are  license(108) packages with a license field and licence(4) *British spelling of license*, So we have 108 packages that could be affected by it.

At the moment the license field is kind of anarchy, some have the name of the license, some have a URL to the license, people have different variations etc.

I could also edit this PR so that it never causes it to fail and only provides helpful messages, and we can add the failures in at a later date?

**Comment by samcv** [comment]
Going to add this comment as a note to myself. Need to implement support for multiple licenses in this code, though we don't have any multi-license designations in the META yet, but they'd be designated:

`Artistic-1.0-Perl OR GPL-1.0` for example would be the licensing that Perl 5 is licensed under.

**Comment by jonathanstowe** [comment]
I  hand merged and made sum changes,

**Pull request closed without merging**
