### PR TITLE
More CI test fixes. Switch to zef

### PR DESCRIPTION
**Pull request by azawawi**
Banana? 👍

### CODE REVIEW

**Comment by jonathanstowe** [comment]
I'm going to leave this one until the CI completes :)

**Comment by azawawi** [comment]
Thanks 👍

**Comment by jonathanstowe** [comment]
I was going to look at the Appveyor thing tomorrow but you saved me from doing it, so thank **you** :+1:

**Comment by azawawi** [comment]
So I saved the famous `RabidGravy` 👍 

Banana? :)

**Pull request merged**
